// frontend/src/components/Editor.tsx
import { useState } from "react";
import type { Document } from "../lib/api";
import styles from "./Editor.module.css";

interface Props {
  doc: Document | null;
  onSave: (title: string, body: string) => void;
}

// The parent renders this with `key={doc?.name}`, so React remounts it (and
// re-initializes this state from props) whenever a different document is
// selected, instead of an effect resetting a stale draft after the fact.
export default function Editor({ doc, onSave }: Props) {
  const [title, setTitle] = useState(doc?.title ?? "");
  const [body, setBody] = useState(doc?.body ?? "");
  const [dirty, setDirty] = useState(false);

  function save() {
    onSave(title, body);
    setDirty(false);
  }

  if (!doc) {
    return <p className={styles.empty}>Select or create a document to start editing.</p>;
  }

  return (
    <div className={styles.editor}>
      <div className={styles.toolbar}>
        <input
          className={styles.title}
          value={title}
          onChange={(e) => {
            setTitle(e.target.value);
            setDirty(true);
          }}
          placeholder="Title"
        />
        <button type="button" className={styles.save} onClick={save} disabled={!dirty}>
          Save
        </button>
      </div>
      <textarea
        value={body}
        onChange={(e) => {
          setBody(e.target.value);
          setDirty(true);
        }}
        placeholder="Write markdown here..."
        rows={24}
      />
    </div>
  );
}

// frontend/src/lib/Editor.svelte
<script lang="ts">
  import type { Document } from "./api";

  let {
    doc,
    onSave,
  }: {
    doc: Document | null;
    onSave: (title: string, body: string) => void;
  } = $props();

  let title = $state("");
  let body = $state("");
  let dirty = $state(false);

  // Reset the local draft whenever a different document is selected.
  $effect(() => {
    title = doc?.title ?? "";
    body = doc?.body ?? "";
    dirty = false;
  });

  function save() {
    onSave(title, body);
    dirty = false;
  }
</script>

{#if doc}
  <div class="editor">
    <input
      class="title"
      bind:value={title}
      oninput={() => (dirty = true)}
      placeholder="Title"
    />
    <textarea
      bind:value={body}
      oninput={() => (dirty = true)}
      placeholder="Write markdown here..."
      rows="20"
    ></textarea>
    <button type="button" onclick={save} disabled={!dirty}>Save</button>
  </div>
{:else}
  <p class="empty">Select or create a document to start editing.</p>
{/if}

<style>
  .editor {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
  .title {
    font-size: 1.1rem;
    font-weight: bold;
  }
  textarea {
    font-family: monospace;
    width: 100%;
    resize: vertical;
  }
  .empty {
    color: var(--muted, #888);
  }
</style>
